packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less

autoInstallPeers: true
nodeLinker: hoisted
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: true
