import 'virtual:uno.css'
import './style.less'
import 'vue/jsx'

export { FormRender, type FormRenderInstance } from './form-render'
export * from './defines'
export * from './hooks'
export * from './interfaces'
export * from './resolver'
export { default } from './install'
