/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModalDemoContent: typeof import('./components/modal-demo-content.vue')['default']
    ModalDemoFooter: typeof import('./components/modal-demo-footer.vue')['default']
    ModalDemoForm: typeof import('./components/modal-demo-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableRender: typeof import('@gopowerteam/table-render')['TableRender']
    Test1: typeof import('./components/test1.vue')['default']
    Test2: typeof import('./components/test2.vue')['default']
  }
}

// For TSX support
declare global {
  const ModalDemoContent: typeof import('./components/modal-demo-content.vue')['default']
  const ModalDemoFooter: typeof import('./components/modal-demo-footer.vue')['default']
  const ModalDemoForm: typeof import('./components/modal-demo-form.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TableRender: typeof import('@gopowerteam/table-render')['TableRender']
  const Test1: typeof import('./components/test1.vue')['default']
  const Test2: typeof import('./components/test2.vue')['default']
}